"""empty message

Revision ID: 3aba587793af
Revises: a064bc6b92d6
Create Date: 2018-10-22 10:14:01.783652

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3aba587793af'
down_revision = 'a064bc6b92d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'description')
    # ### end Alembic commands ###
