"""empty message

Revision ID: a064bc6b92d6
Revises: 88191ee6b5ad
Create Date: 2018-10-17 19:19:37.862631

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a064bc6b92d6'
down_revision = '88191ee6b5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body', sa.Text(), nullable=False))
    op.drop_column('article', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('article', 'body')
    # ### end Alembic commands ###
